pybo/views/answer_views.py
# Created by user at 2024-02-15
import functools
from datetime import datetime
from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from pybo import db
from pybo.models import Question,Answer
from ..forms import AnswerForm

bp = Blueprint('answer',__name__,url_prefix='/answer')







#로그인 필수 처리 데코레이터 : @login_required
def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        #login여부 check
        if g.user is None:
            _next =request.url if request.method == 'GET' else ''
            print(f'_next:{_next}')
            return redirect(url_for('auth.login',next=_next))

        return view(*args, **kwargs)

    return wrapped_view

#답변 추천
@bp.route('/vote/<int:answer_id>')
@login_required
def vote(answer_id):
    _answer = Answer.query.get_or_404(answer_id)

    if g.user == _answer.user:
        flash('본인이 작성한 글은 추천할수 없습니다.')
    else:
        _answer.voter.append(g.user)
        db.session.commit()

    return redirect(url_for('question.detail',question_id=_answer.question.id))


#삭제: delete
@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)

    question_id=answer.question.id

    if g.user != answer.user:
        flash('삭제 권한이 없습니다.')
    else:
        db.session.delete(answer)
        db.session.commit()

    return redirect( url_for('question.detail',question_id=question_id))


#수정: modify
@bp.route('/modify/<int:answer_id>',methods=('GET','POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)

    #본인의 답변글만 수정
    if g.user != answer.user:
        flash('수정 권한이 없습니다.')
        return redirect( url_for('question.detail',question_id=answer.question.id))
    if request.method == 'POST': #POST 처리
        form = AnswerForm()

        if form.validate_on_submit():
            form.populate_obj(answer) #form데이터를 수정
            answer.modify_date = datetime.now() #수정일
            db.session.commit()
            #질문 상셍
            return redirect( url_for('question.detail',question_id=answer.question.id))

    else: #GET 방식
        form = AnswerForm(obj=answer)

    return render_template('answer/answer_form.html', form=form)







@bp.route('/create/<int:question_id>',methods=('POST',))
@login_required
def create(question_id):
    print('-'*50)
    print(f'question_id:{question_id}')
    print('-'*50)

    form = AnswerForm()

    question = Question.query.get_or_404(question_id)

    #content
    #request : request객체는 플라스크 내장 객체, 브라우저 요청을 처리

    if form.validate_on_submit():
        contents = request.form['contents']
        print(f'contents:{contents}')

        #답변등록
        answer=Answer(question=question, contents=contents, create_date=datetime.now(),user=g.user)
        db.session.add(answer) #저장
        db.session.commit() #commit
        return redirect(url_for('question.detail',question_id=question_id))


    return render_template('question/question_detail.html',question=question, form=form)

pybo/views/question_views.py
# Created by user at 2024-02-15
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from pybo.models import Question
from pybo.forms import QuestionForm,AnswerForm
from .answer_views import login_required
from .. import db

bp = Blueprint('question',__name__,url_prefix='/question')



#질문 추천 라우팅 함수
@bp.route('/vote/<int:question_id>')
@login_required
def vote(question_id):
    _question = Question.query.get_or_404(question_id)
    #본인이 작성한 글은 추천 불가
    if g.user == _question.user:
        flash('본인이 작성한 글은 추천 불가 합니다.')
    else:
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail',question_id=question_id))


#삭제: delete
@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):

    question = Question.query.get_or_404(question_id) #question_id에 해당하는 데이터 단건조회

    #권한: 글쓴이만 삭제 가능
    if g.user != question.user:
        flash('삭제권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))


    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))



#수정:question_form.html같이 사용
@bp.route('/modify/<int:question_id>',methods=('GET','POST'))
@login_required
def modify(question_id):
    print('-'*30)
    print(f'question_id:{question_id}')
    print(f'request.method:{request.method}')
    print('-' * 30)
    question = Question.query.get_or_404(question_id)

    #수정 권한 체크
    if g.user != question.user:
        flash('수정권한이 없습니다.')
        return redirect( url_for('question.detail',question_id=question_id))


    if request.method == 'POST':  #POST
        form = QuestionForm()

        if form.validate_on_submit():
            #수정: form변수 들어 있는 데이터를 question객체에 update역할
            form.populate_obj(question) #화면에서 들어오는 질문 제목, 내용 update
            question.modify_date = datetime.now() #수정일시
            print(f'question:{question}')
            db.session.commit()
            return redirect( url_for('question.detail',question_id=question_id))



    else: #GET
        form = QuestionForm(obj=question)

    return render_template('question/question_form.html',form=form)



#@login_required @bp.route뒤에 위치해야 한다. 그렇치 않으면 정상 동작 하지 않는다.
@bp.route('/create',methods=('GET','POST'))
@login_required
def create():
    form = QuestionForm()

    print(f'request:{request.method}')
    print(f'form.validate_on_submit:{form.validate_on_submit()}')
    #request method가 post이고 form이 submit()이면
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data,contents=form.contents.data
                            ,create_date=datetime.now(),user=g.user)
        db.session.add(question)
        db.session.commit()

        print(f'main.index:{url_for('main.index')}')
        return redirect( url_for('main.index'))

    return render_template('question/question_form.html', form=form)

#/question/detail/1
@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    print(f'question_id:{question_id}')
    #단건 조회
    question = Question.query.get_or_404(question_id)
    print(f'question:{question}')

    return render_template('question/question_detail.html',question=question, form=form)

#/question/list
#list는 파이썬 예약어
@bp.route('/list')
def _list():
    #질문 목록을 날짜 역순으로 출력
    #Question.create_date.asc()
    question_list=Question.query.order_by(Question.create_date.desc())

    #paging: http://127.0.0.1:5000/question/list?page=1
    page = request.args.get('page', type=int, default=1)
    question_list=question_list.paginate(page=page, per_page=10)

    #화면으로, question_list 데이터 전달
    return render_template('question/question_list.html',question_list=question_list)

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3" xmlns="">
        <!-- flash 오류 -->
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
        {% endfor %}
        <!-- 질문 -->
        <h2 class="border-bottom py-2">{{question.subject}}</h2>
        <div class="card my-3">
            <div class="card-body">
                <!--white-space:pre-line: 글 내용의 줄 바꿈을 정상적-->
                <div class="card-text" >{{question.contents|markdown}}</div>
                <div class="d-flex justify-content-end">
                    <!-- 수정일 -->
                    {% if question.modify_date %}
                    <div class="badge bg-light text-dark p-2 text-start  mx-3">
                        <div class="mb-2">수정일</div>
                        <div >{{question.modify_date|datetime}}</div>
                    </div>
                    {% endif %}
                    <div class="badge bg-light text-dark p-2 text-start">
                        <div class="mb-2">{{question.user.username}}</div>
                        <div >{{question.create_date|datetime}}</div>
                    </div>
                </div>
                <!-- 수정은 글을 등록한 사람만 수정 가능-->
                <div class="my-3">
                    <a href="javascript:void(0)" data-uri="{{ url_for('question.vote',question_id=question.id)}}"
                       class="recommend btn btn-sm btn-outline-secondary">추천
                        <span class="badge rounded-pill bg-success">{{question.voter|length}}</span>
                    </a>

                    {% if g.user == question.user %}
                     <a href="{{ url_for('question.modify',question_id=question.id) }}"  class="btn btn-sm btn-outline-secondary">수정</a>
                     <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                      data-uri = '{{ url_for('question.delete',question_id=question.id)  }}'
                     >삭제</a>

                    {% endif %}
                </div>
            </div>

        </div>
        <!-- 질문 --------------------------------------------------------------------->

        <!--답변-->
        <h5 class="border-bottom my-3 py-2">{{question.answer_set|length}}개의 답변</h5>
        <div>
                {% for answer in question.answer_set%}
                   <div class="card my-3">
                       <div class="card-body">
                           <div class="card-text" >{{answer.contents|markdown}}</div>
                           <div class="d-flex justify-content-end">
                            <!-- 수정일 -->
                            {% if answer.modify_date %}
                            <div class="badge bg-light text-dark p-2 text-start mx-3">
                                <div class="mb-2">수정일</div>
                                <div >{{answer.modify_date|datetime}}</div>
                            </div>
                            {% endif %}

                               <div class="badge bg-light text-dark p-2 text-start">
                                   <div class="mb-2">{{answer.user.username}}</div>
                                   <div >{{answer.create_date|datetime}}</div>
                               </div>
                           </div>

                           <!--답변 수정-->
                           <div class="my-3">
                               <a href="javascript:void(0)" data-uri="{{ url_for('answer.vote',answer_id=answer.id)  }}"
                                  class="recommend btn btn-sm btn-outline-secondary">추천
                               <span class="badge rounded-pill bg-success">{{answer.voter|length}}</span>
                               </a>
                               {% if g.user == answer.user %}
                               <a href="{{ url_for('answer.modify',answer_id=answer.id) }}" class="btn btn-sm btn-outline-secondary" >수정</a>
                               <a href="#" class="delete btn btn-sm btn-outline-secondary"
                               data-uri="{{ url_for('answer.delete',answer_id=answer.id )}}"
                               >삭제</a>
                               {% endif %}
                           </div>


                       </div>
                   </div>
                {% endfor %}
        </div>
        <!-- 답변 --------------------------------------------------------------------->

        <!-- 답변등록 -->
        <form class="my-3" action="{{url_for('answer.create',question_id=question.id)}}" method="post" >
            {{form.csrf_token()}}
            <!--오류표시 -->
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field,errors in form.errors.items()%}
                        <strong>{{form[field].label}}</strong>
                        <ul>
                            {% for error in errors%}
                                <li>{{error}}</li>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                </div>
            {% endif %}


            <!--오류표시 --------------------------------------------------->
            <div class="mb-3">
                <textarea {% if not g.user %}  disabled {% endif %} name="contents" id="contents" rows="3" class="form-control"></textarea>
                {{ simplemde.load }}
            </div>
            <input type="submit" value="답변등록" class="btn btn-primary">
        </form>
    </div>

{% endblock %}

{% block script %}
    <script>
        //recommend
        const recommendElements = document.getElementsByClassName('recommend');
        Array.from(recommendElements).forEach(function(element){
            element.addEventListener('click', function(){
                 console.log('recommendElements click:'+this.dataset.uri);
                  if(confirm('추천 하시겠습니까?')){
                       location.href = this.dataset.uri;
                  }
            });
        });

        const deleteEmements = document.getElementsByClassName('delete');
        //Array.from(deleteEmements) : deleteEmements를 배열 요소로 변환
        Array.from(deleteEmements).forEach(function(element){
            element.addEventListener('click', function(){
                console.log('deleteEmements click');
                console.log('this.dataset.uri:'+this.dataset.uri);
                if(confirm('삭제 하시겠습니까?')){
                    location.href = this.dataset.uri;
                }
            });
        });
    </script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<!--질문등록 -->
<div class="container">
    <h5 class="my-3 border-bottom">질문등록</h5>

    <!--action속성이 없으면, 현재 페이지의 URL이 default action으로 설정된다.
        <form method="post" action="{{ url_for('question.create') }}">
        생략해서 사용: 수정, 등록에 사용
    -->
    <!--http://127.0.0.1:5000/question/create -->
    <form method="post" class="post-form my-3" >
        {{form.csrf_token}}
        <!-- validate 처리-->
        {% include "form_errors.html" %}
        <!-- validate 처리---------------------------------------------------------------->
        <div class="mb-3">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{form.subject.data or ''}}">
        </div>
        <div class="mb-3">
            <label for="contents">내용</label>
            <textarea class="form-control" name="contents" id="contents" rows="7">{{form.contents.data or ''}}</textarea>
            {{ simplemde.load }}
        </div>
        <button type="submit" class="btn btn-primary">저장</button>
    </form>
</div>

{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
    <div class ="container my-3">
        <table class=" table">
            <thead>
                <tr class="text-center table-dark">
                    <th>번호</th>
                    <th style="width:50%">제목</th>
                    <th>글쓴이</th>
                    <th>작성일시</th>
                </tr>
            </thead>
            <tbody>
                <!--질문 목록 -->
                {% if question_list  %}
                        <!--text-start,text-center,text-end: 왼쪽, 가운데, 오른쪽-->
                        {% for question in question_list.items %}
                            <tr>
                                <td  class="text-center">{{question_list.total - ((question_list.page -1 ) * question_list.per_page) -  loop.index0}}</td>
                                <td  class="text-start"><a href="{{url_for('question.detail',question_id=question.id)}}">{{question.subject}}</a>
                                    <!--답변 개수 -->
                                    {% if question.answer_set|length >0 %}
                                      <span class="text-danger small mx-2">{{question.answer_set|length}}</span>
                                    {% endif %}
                                </td>
                                <td class="text-center">{{question.user.username}}</td> <!-- 글쓴이 -->
                                <td class="text-center">{{question.create_date|datetime}}</td>
                            </tr>
                        {% endfor %}
                {% else  %}
                        <tr>
                            <td colspan="99">질문이 없습니다.</td>
                        </tr>
                {% endif %}
            </tbody>
        </table>
        <!--페이징  -->
        <!--
        question_list.has_prev:{{question_list.has_prev}}<br/>
        question_list.has_next:{{question_list.has_next}}<br/>
        -->

        <ul class="pagination justify-content-center">
            <!--이전 -->
            {% if question_list.has_prev %}
               <li class="page-item">
                    <a class="page-link" href="?page={{question_list.prev_num}}">이전</a>
               </li>
            {% else %}
               <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0);">이전</a>
               </li>
            {% endif %}
            <!--이전 -->

            <!--페이지 번호 -->
            {% for page_num in question_list.iter_pages() %}
                {% if page_num %}
                    <!--현재 page인 경우, 그렇치 않은 경우 -->
                    {% if  page_num != question_list.page %}
                       <li class="page-item">
                            <a class="page-link" href="?page={{page_num}}">{{page_num}}</a>
                       </li>
                    {% else %}
                       <li class="page-item active" aria-current="page">
                            <a class="page-link" href="javascript:void(0);">{{page_num}}</a>
                       </li>
                    {% endif %}
                {% else %}
                       <li class="disabled">
                            <a class="page-link" href="javascript:void(0);">...</a>
                       </li>
                {% endif %}

            {% endfor %}
            <!--페이지번호 -->

            <!--다음페이지 -->
            {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{question_list.next_num}}">다음</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0);">다음</a>
                </li>
            {% endif %}
            <!--//다음페이지 -->
        </ul>
        <!--//페이징  ---------------------------------------------------------------------->
        <a href="{{url_for('question.create')}}"  class="btn btn-primary">질문등록</a>
    </div>
{% endblock %}