pybo/views/auth_views.py
# Created by user at 2024-02-19

#g변수는 : 플라스크의 컨텍스트 변수
from flask import Blueprint,url_for,render_template,flash,request,session,g
from werkzeug.security import generate_password_hash,check_password_hash
from werkzeug.utils import redirect

from pybo import db
from pybo.forms import UserCreateForm,UserLoginForm
from pybo.models import User

bp = Blueprint('auth',__name__,url_prefix='/auth')




@bp.route('/logout')
def logout():
    session.clear() # session 삭제
    return redirect( url_for('main.index'))

#로그인 여부 확인
#@bp.before_app_request : 모든 request전에 수행되는 기능의 어노테이션
@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id);

@bp.route('/login',methods=("GET","POST"))
def login():
    form = UserLoginForm()
    #로그인 화면에서 로그인 버튼 click
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        print('-'*50)
        print(f'email:{form.email.data}')
        print(f'password:{form.password.data}')
        print('-' * 50)

        #email존재 유무 check
        user=User.query.filter_by(email = form.email.data).first()
        print(f'user:{user}')
        #flag = check_password_hash(user.password, form.password.data)
        #print(f'flag:{flag}')

        if not user:
            error = '존재하지 않는 사용자입니다.'
        elif not check_password_hash(user.password, form.password.data):
            error = '비밀번호를 확인 하세요.'

        #로그인 session처리
        if error is None:
            session.clear() #session clear
            session['user_id'] = user.id #session : user_id

            _next = request.args.get('next','')

            #_next 유무에 따라 : next 파라미터 값이 없으며 메인 페이지로, 있으면, 로그인 후 해당 페이지로

            if _next :
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))

        #error 메시지 전달
        flash(error)


    return render_template('auth/login.html',form=form)

#GET: 화면 등록 화면
#POST : 회원가입 저장
@bp.route('/signup',methods=('GET','POST'))
def signup():
    form = UserCreateForm()

    #회원가입 저장
    if request.method == 'POST' and form.validate_on_submit():
        #사용자가 존재 하는지 확인
        # email중복 체크
        user = User.query.filter_by(email=form.email.data).first()
        print('-' * 50)
        print(f'username:{form.username.data}')
        print(f'password1:{form.password1.data}')
        print(f'generate_password_hash:{generate_password_hash(form.password1.data)}')
        print(f'email:{form.email.data}')
        print('-' * 50)
        print(f'user:{user}')

        if not user:


            user=User(username=form.username.data,
                      password=generate_password_hash(form.password1.data),
                      email = form.email.data)
            #db저장, commit
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash(f'이미 존재하는 사용자 입니다.({user.username})')

    return render_template('auth/signup.html',form=form)

pybo/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--bootstrap-->
    <link rel="stylesheet" href="{{url_for('static',filename='bootstrap.min.css')}}">
    <!--기본css -->
    <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}">
    <link rel="shortcut icon" type="image/x-icon" href="{{url_for('static',filename='favicon.ico')}}" >
    {{ simplemde.css }}
    {{ simplemde.js }}
    <title>PCWK</title>
</head>
<body>

<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!--//네비게이션 -->

    {% block content %}
    {% endblock%}

    <!--bootstrap 자바스크립트: 반응형 메뉴처리(햄버거)-->
    <script src="{{url_for('static',filename='bootstrap.min.js')}}"></script>
    <!-- 자바스크립트 -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 end -->
</body>
</html>

pybo/templates/form_errors.html
        <!-- validate 처리-->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors   in form.errors.items() %}
                <strong>{{form[field].label}}</strong>
                <ul>
                    {% for error in errors%}
                        <li>{{error}}</li>
                    {% endfor %}
                </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- validate 처리---------------------------------------------------------------->
        <!-- flash 오류 -->
        {% for message in get_flashed_messages() %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
        {% endfor %}

pybo/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">PCWK</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- login된 경우 -->
            {% if g.user %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout')  }}">{{g.user.username}} [로그아웃]</a>
                </li>
            </ul>
            {% else %}
            <!-- login안된경우 -->
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">계정생성</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login')}}">로그인</a>
                </li>
            </ul>
            {% endif %}


        </div>
    </div>
</nav>